
using JosephM.Core.Attributes;
using JosephM.Core.FieldType;
using JosephM.Record.Attributes;
using JosephM.Record.Query;
using JosephM.Xrm.Schema;
using JosephM.XrmModule.SavedXrmConnections;
using System.Collections.Generic;

namespace JosephM.Xrm.Vsix.Module.PackageSettings
{
    [Instruction("Enter Settings Used By The Visual Studio Extention\n\nThese Settings Are Specific For This Solution And Will Be Stored In A File In A SolutionItems Folder")]
    [Group(Sections.ObjectPrefixes, true, 20)]
    [Group(Sections.Solution, true, 10)]
    [Group(Sections.ConnectionInstances, true, 30)]
    public class XrmPackageSettings : ISavedXrmConnections
    {
        [MyDescription("Select If Items Deployed Into Dynamics Will Be Added Into A Solution")]
        [Group(Sections.Solution)]
        public bool AddToSolution { get; set; }

        [MyDescription("Select The Solution To Add Deployed Items Into")]
        [Group(Sections.Solution)]
        [RequiredProperty]
        [ReferencedType(Entities.solution)]
        [UsePicklist(Fields.solution_.uniquename)]
        [LookupCondition(Fields.solution_.ismanaged, false)]
        [LookupCondition(Fields.solution_.isvisible, true)]
        [LookupCondition(Fields.solution_.uniquename, ConditionType.NotEqual, "default")]
        [PropertyInContextByPropertyValue(nameof(AddToSolution), true)]
        public Lookup Solution { get; set; }

        [MyDescription("String Used To Prefix The Names Of Objects Generated By Project And Item Templates")]
        [Group(Sections.ObjectPrefixes)]
        [RequiredProperty]
        [DisplayName("Class Prefix")]
        public string SolutionObjectPrefix { get; set; }
        [MyDescription("String Used To Prefix The Names Of Deployable Files Generated By Project And Item Templates")]
        [Group(Sections.ObjectPrefixes)]
        [RequiredProperty]
        [DisplayName("Customisation Prefix")]
        public string SolutionDynamicsCrmPrefix { get; set; }

        [Hidden]
        public string SolutionObjectInstancePrefix
        {
            get
            {
                if (string.IsNullOrEmpty(SolutionObjectPrefix))
                    return SolutionObjectPrefix;
                if (char.IsLower(SolutionObjectPrefix[0]))
                    return "" + char.ToUpper(SolutionObjectPrefix[0]) + (SolutionObjectPrefix.Length == 1 ? "" : SolutionObjectPrefix.Substring(1));
                if (char.IsUpper(SolutionObjectPrefix[0]))
                    return "" + char.ToLower(SolutionObjectPrefix[0]) + (SolutionObjectPrefix.Length == 1 ? "" : SolutionObjectPrefix.Substring(1));
                return SolutionObjectPrefix;
            }
        }

        [FormEntry]
        [Group(Sections.ConnectionInstances)]
        public IEnumerable<SavedXrmRecordConfiguration> Connections { get; set; }

        private static class Sections
        {
            public const string ObjectPrefixes = "Prefixes";
            public const string Solution = "Active Dev Solution";
            public const string ConnectionInstances = "Instance Connections";
        }
    }
}